package com.github.benshi.mybatis.example.model;

import java.time.LocalDateTime;
import lombok.Data;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import lombok.experimental.Accessors;
import java.util.Optional;
import com.github.benshi.mybatis.AutoGenMapper;
import com.github.benshi.mybatis.AutoGenColumn;
import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;


/**
 *
 * Generated by gen-myBatis generator on 2025-03-24 02:59:34
 *
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@Builder
@JsonAutoDetect(fieldVisibility = Visibility.ANY, getterVisibility = Visibility.NONE, setterVisibility = Visibility.NONE)
@AutoGenMapper(table = "user")
public class User {

    /**
     * 主键
     */
    @AutoGenColumn(name = "id", type = "BIGINT", nullable = false, pk = true)
    @lombok.NonNull
    private Long id;

    /**
     * 名称
     */
    @AutoGenColumn(name = "name", type = "VARCHAR", nullable = false)
    @lombok.NonNull
    private String name;

    /**
     * 年龄
     * 123
     */
    @AutoGenColumn(name = "age", type = "INT", nullable = false)
    @lombok.NonNull
    private Integer age;

    /**
     * 创建时间
     */
    @AutoGenColumn(name = "create_time", type = "TIMESTAMP")
    private LocalDateTime createTime;

    /**
     * 更新时间
     */
    @AutoGenColumn(name = "update_time", type = "TIMESTAMP")
    private LocalDateTime updateTime;

    public Optional<Long> getIdOptional() {
        return Optional.ofNullable(id);
    }

    public void setIdOptional(Optional<Long> idOptional) {
        if (idOptional == null) {
            this.id = null;
            return;
        }

        this.id = idOptional.orElse(null);
    }
    
    public Optional<String> getNameOptional() {
        return Optional.ofNullable(name);
    }

    public void setNameOptional(Optional<String> nameOptional) {
        if (nameOptional == null) {
            this.name = null;
            return;
        }

        this.name = nameOptional.orElse(null);
    }
    
    public Optional<Integer> getAgeOptional() {
        return Optional.ofNullable(age);
    }

    public void setAgeOptional(Optional<Integer> ageOptional) {
        if (ageOptional == null) {
            this.age = null;
            return;
        }

        this.age = ageOptional.orElse(null);
    }
    
    public Optional<LocalDateTime> getCreateTimeOptional() {
        return Optional.ofNullable(createTime);
    }

    public void setCreateTimeOptional(Optional<LocalDateTime> createTimeOptional) {
        if (createTimeOptional == null) {
            this.createTime = null;
            return;
        }

        this.createTime = createTimeOptional.orElse(null);
    }
    
    public Optional<LocalDateTime> getUpdateTimeOptional() {
        return Optional.ofNullable(updateTime);
    }

    public void setUpdateTimeOptional(Optional<LocalDateTime> updateTimeOptional) {
        if (updateTimeOptional == null) {
            this.updateTime = null;
            return;
        }

        this.updateTime = updateTimeOptional.orElse(null);
    }
    
}