### insert
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": 1,
  "name": "John",
  "age": 30
}


### select all
GET http://localhost:8080/api/users
Accept: application/json


### select by id
GET http://localhost:8080/api/users/1

### update
POST http://localhost:8080/api/users/update
Content-Type: application/json

{
  "id": 1,
  "name": "John1",
  "age": 31
}

### delete
POST  http://localhost:8080/api/users/delete/1

### get all count
GET http://localhost:8080/api/users/count
Accept: application/json